---
title: "Problem set 4"
author: "Logan Langholz"
date: "`r Sys.Date()`"
---

# Overview

For this problem set you will need to analyze some ChIP-seq data to
identify a mystery factor X.

## Workflow

Create a `run.sh` file that runs the entire workflow (or as much as possible).

### Alignment

Align FASTQ data to the human genome with bowtie2. There are two files
in the `data/` directory:

```
data/factorx.chr1.fq.gz
data/hg19.chr1.fa.gz
```

First build a bowtie2 index with `bowtie2-build` and use `bowtie2` and `samtools` to align the reads to the index.

**The output of the alignment step is a sorted BAM file.**

### Create bedGraph

Create a bedGraph file from the sorted BAM files. Use the
`bedGraphToBigWig` utility and the `hg19.chrom.size` file in the `data/`
directory.

### Create a track in the UCSC browser

1. Create a branch in your forked repository called `gh-pages`:

```bash
$ git branch gh-pages
$ git push origin gh-pages
```

1. Go to the browser and add a "custom track" in the `hg19` genome build.
your trackline should look something like this (all on one line):

```
track type=bedGraph bigDataUrl="http://<username>.github.io/<repo name>/path/to/bw color=255,0,0 visiblity=full name='chip data' description='chip description'
```

### Peak calling

Call peaks from the bedGraph data using MACS2.

```bash
$ macs2 callpeak -t <BAM file>
```


### Generate motifs from the peak calls

1. Use these peak calls to collect FASTA sequences with `bedtools getfasta`.

1. Derive motifs from the FASTA sequences with `meme`.

```bash
# if you get an error about "max size" add -maxsize 1000000
$ meme <FASTA file> -nmotifs 1 -maxw 20 -minw 8 -dna 
```

1. Extract the motif from the `meme.txt` output and use TOMTOM to identify
the motif match. You can use the `meme-get-motif` to extract the first motif from the file:

```bash
meme-get-motif -id 1 < meme.txt
```

Copy the numeric matrix into the the search box on the tomtom site and report which motif it matches.

--------------------------------------
Below is the run.sh file to accomplish the above tasks: 

```bash
#! /usr/bin/env bash
 
#Files: Note, files were unzipped before beginning
reference='/Users/loganlangholz/Documents/class_files/Graduate/Spring_2016/Genome_analysis/Projects/problem-set-4/data/hg19.chr1.fa'
fastq='/Users/loganlangholz/Documents/class_files/Graduate/Spring_2016/Genome_analysis/Projects/problem-set-4/data/factorx.chr1.fq'
chr_sizes='/Users/loganlangholz/Documents/class_files/Graduate/Spring_2016/Genome_analysis/Projects/problem-set-4/data/hg19.chrom.sizes'
   
#Build index and align reads:
bowtie2-build -f $reference chr1_index
bowtie2 -x chr1_index -U $fastq \
    | samtools sort > output.bam
 
#Create bedGraph, then BigWig fiels:
bedtools genomecov -ibam output.bam -bg > output.bg
bedGraphToBigWig output.bg $chr_sizes output.bw
 
#call peaks:
macs2 callpeak -t output.bam --nomodel -n factorx
  
#shuffle peaks and take only top 1000, add slop (50bp each side), put in new file
shuf factorx_summits.bed | head -n 1000 \
    | awk 'BEGIN {OFS="\t"} {print $1, $2-50, $3+50, $4, $5}' \
    > factorx_shuf_peaks.bed
 
# Get Fasta sequence for the shuffled peaks:
bedtools getfasta -fi $reference -bed factorx_shuf_peaks.bed -fo factorx.fa
 
# Plug fasta file into meme to get motifs
meme factorx.fa -nmotifs 1 -maxw 20 -minw 8 -dna -maxsize 1000000
meme-get-motif -id 1 < meme_out/meme.txt
```
Plugging the meme output into TomTom yields the 'CTCF' motif, with a corresponding p-value of 1.8x10^-12
